{
  failed(getException());
  finished();
  fireEvent(new TaskCompletionEvent<V>(this,TaskCompletionEvent.FAILED,null,getException()));
}
